package net.vaier.domain.port;

import java.util.Optional;

/**
 * A driven port for reading the key that decrypts Vaier's own configuration store — the vault key behind
 * every {@code enc:v1:} value in it.
 *
 * <p>It exists for one reader: the survival kit. Restoring Vaier from one of its own backup archives yields
 * a configuration whose credentials and repository passphrases are all ciphertext, and without
 * this key that restore stops there. The archives themselves need only their own passphrases, which the kit
 * also carries — this is for the step after.
 *
 * <p>The key is <em>read, never minted</em>. A key generated by the act of writing a kit would decrypt
 * nothing, printed on the one page claiming to decrypt everything, so an absent key is reported as absent.
 */
public interface ForReadingTheConfigKey {

    /** The configuration key as it is stored, or empty when Vaier has not generated one yet. */
    Optional<String> configKey();
}
