package net.vaier.adapter.driven;

import net.vaier.domain.AuthMethod;
import net.vaier.domain.SshAuthException;
import net.vaier.domain.SshTarget;
import org.apache.sshd.common.config.keys.KeyUtils;
import org.apache.sshd.common.config.keys.writer.openssh.OpenSSHKeyPairResourceWriter;
import org.apache.sshd.common.keyprovider.KeyPairProvider;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.util.Collection;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * #350 — which private-key formats Vaier can actually read. Every path that reaches a machine over SSH
 * funnels through {@link SshConnector#loadKeyPairs}, so a format that fails here fails the web terminal,
 * remote commands, Explorer listings and backup runs alike — and only at connect time, long after the
 * credential appeared to save cleanly.
 *
 * <p>ed25519 is what {@code ssh-keygen} produces by default and what the credential dialog's placeholder
 * invites, so it is the format that matters most.
 */
class SshConnectorKeyParsingTest {

    /**
     * A throwaway ed25519 key generated by {@code ssh-keygen -t ed25519 -N ''} purely as test material.
     * It authorises nothing, anywhere, and must never be reused for any other purpose. ed25519 is the one
     * format that cannot be minted in-test without the very dependency under test, hence a fixture.
     */
    private static final Path ED25519_FIXTURE =
        Path.of("src/test/resources/ssh-keys/throwaway-ed25519.pem");

    @Test
    void parsesAnEd25519OpenSshPrivateKey() throws Exception {
        String pem = Files.readString(ED25519_FIXTURE, StandardCharsets.UTF_8);

        Collection<KeyPair> keys = SshConnector.loadKeyPairs(targetWithKey(pem));

        assertThat(keys).hasSize(1);
        assertThat(KeyUtils.getKeyType(keys.iterator().next()))
            .isEqualTo(KeyPairProvider.SSH_ED25519);
    }

    @Test
    void parsesAnRsaOpenSshPrivateKey() throws Exception {
        String pem = opensshPrivateKey(KeyUtils.generateKeyPair(KeyPairProvider.SSH_RSA, 2048));

        Collection<KeyPair> keys = SshConnector.loadKeyPairs(targetWithKey(pem));

        assertThat(keys).hasSize(1);
        assertThat(KeyUtils.getKeyType(keys.iterator().next())).isEqualTo(KeyPairProvider.SSH_RSA);
    }

    @Test
    void parsesAnEcdsaOpenSshPrivateKey() throws Exception {
        String pem = opensshPrivateKey(KeyUtils.generateKeyPair(KeyPairProvider.ECDSA_SHA2_NISTP256, 256));

        Collection<KeyPair> keys = SshConnector.loadKeyPairs(targetWithKey(pem));

        assertThat(keys).hasSize(1);
        assertThat(KeyUtils.getKeyType(keys.iterator().next()))
            .isEqualTo(KeyPairProvider.ECDSA_SHA2_NISTP256);
    }

    @Test
    void unparseableKeyMaterialSaysWhatVaierExpects() {
        assertThatThrownBy(() -> SshConnector.loadKeyPairs(targetWithKey("not a key at all")))
            .isInstanceOf(SshAuthException.class)
            .hasMessageContaining("PRIVATE KEY")
            .hasMessageContaining("ed25519")
            .hasMessageContaining(".pub");
    }

    @Test
    void aPublicKeyStoredAsTheSecretSaysItIsThePublicHalf() throws Exception {
        // The single most likely mistake, and the one that produced #350's symptom: the .pub file pasted.
        String pub = Files.readString(
            Path.of("src/test/resources/ssh-keys/throwaway-ed25519.pem.pub"), StandardCharsets.UTF_8);

        assertThatThrownBy(() -> SshConnector.loadKeyPairs(targetWithKey(pub)))
            .isInstanceOf(SshAuthException.class)
            .hasMessageContaining(".pub");
    }

    private static SshTarget targetWithKey(String pem) {
        return new SshTarget("nas.example.test", 22, "admin", AuthMethod.PRIVATE_KEY, pem, null, null);
    }

    private static String opensshPrivateKey(KeyPair keyPair) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        OpenSSHKeyPairResourceWriter.INSTANCE.writePrivateKey(keyPair, "vaier-test", null, out);
        return out.toString(StandardCharsets.UTF_8);
    }
}
